name: TAS-Nightly-Build-Windows

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Get Date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1.4.0
        with:
          format: "YYYY_MM_DD"

      - name: Clone TheAnimeScripter repository
        uses: actions/checkout@v4
        with:
          repository: NevermindNilas/TheAnimeScripter
          path: TheAnimeScripter
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Run build script
        run: |
          cd TheAnimeScripter
          python build.py --output dist-full

      - name: Run lite build script
        run: |
          cd TheAnimeScripter
          python build-lite.py --output dist-lite

      - name: Compress full directory
        run: |
          cd TheAnimeScripter/dist-full/main/
          7z a -t7z -m0=lzma2 -mx=9 -ms=1536m -md=273m ../../../TAS_Full_${{ steps.date.outputs.time }}.7z *

      - name: Compress lite directory
        run: |
          cd TheAnimeScripter/dist-lite/main/
          7z a -t7z -m0=lzma2 -mx=9 -ms=1536m -md=273m ../../../TAS_Lite_${{ steps.date.outputs.time }}.7z *

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: TAS_${{ steps.date.outputs.time }}
          name: TAS_${{ steps.date.outputs.time }}
          draft: false
          prerelease: false
          files: |
            TAS_Full_${{ steps.date.outputs.time }}.7z
            TAS_Lite_${{ steps.date.outputs.time }}.7z

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}