name: TAS-Nightly-Build-Windows

on:
  schedule:
    - cron: '0 */18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Clone TheAnimeScripter repository
        with:
          repository: NevermindNilas/TheAnimeScripter
          path: TheAnimeScripter
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.9"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Pip Install Requirements-Dev
        run: |
          cd TheAnimeScripter
          python -m pip install --no-deps -r requirements-dev-windows.txt
          python -m pip install -r requirements-dev-windows.txt --no-cache-dir

      - name: Sanity Check - List pip modules
        run: python -m pip list

      - name: Run build script
        run: |
          cd TheAnimeScripter
          python build.py --venv

      - name: Get the date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Compress main directory
        run: |
          cd TheAnimeScripter/dist/main/
          7z a -t7z -m0=lzma2 -mx=9 -ms=1536m -md=273m ../../../TAS_${{ steps.date.outputs.date }}.7z *

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: TAS_${{ steps.date.outputs.date }}
          name: TAS_${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          files: TAS_${{ steps.date.outputs.date }}.7z

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}