name: TAS-Nightly-Build-Windows

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout TAS-Nightly repository
        uses: actions/checkout@v4

      - name: Clone TheAnimeScripter repository
        uses: actions/checkout@v4
        with:
          repository: NevermindNilas/TheAnimeScripter
          path: TheAnimeScripter
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.9"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Pip Install Requirements-Dev
        run: |
          cd TheAnimeScripter
          python -m pip install --no-deps -r requirements-dev-windows.txt
          python -m pip install -r requirements-dev-windows.txt --no-cache-dir

      - name: Sanity Check - List pip modules
        run: python -m pip list

      - name: Run build script
        run: |
          cd TheAnimeScripter
          python build.py --venv

      - name: Get the date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Compress main directory
        run: |
          cd TheAnimeScripter/dist/main/
          7z a -t7z -m0=lzma2 -mx=9 -ms=1536m -md=273m ../../../TAS_${{ steps.date.outputs.date }}.7z *

      - name: Read CHANGELOG.md
        id: changelog
        run: |
          $changelog = Get-Content TheAnimeScripter/CHANGELOG.MD -Raw
          $changelog = $changelog -replace "`r`n","\n"
          $changelog = $changelog -replace '"','\"'
          echo "content=$changelog" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: TAS_${{ steps.date.outputs.date }}
          release_name: TAS_${{ steps.date.outputs.date }}
          body: |
            This is a nightly build of TheAnimeScripter. It may contain bugs and is not recommended for production use.

            Current CHANGELOG:
            ```
            ${{ steps.changelog.outputs.content }}
            ```
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TAS_${{ steps.date.outputs.date }}.7z
          asset_name: TAS_${{ steps.date.outputs.date }}.7z
          asset_content_type: application/x-7z-compressed

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}